### ISSUE TITLE
Malware Archive not showing archived files + related issues & feedback

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#191]
This is more or less a few issues, but I believe they can be connected. 

General context: the setup was updated from AL stable90 to stable91, it runs on Docker Compose and ES 7.x. Archiver is running, the archive data store is enabled as well as the archive file store - both for about three months.

Extraction from config.yaml:
```yaml
datastore:
  hosts: ["http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200"]
  archive:
    enabled: true

filestore:
  cache: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-storage&use_ssl=False"]
  archive: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-archive&use_ssl=False"]
```

## Not showing freshly archived files until including supplementary

**Describe the bug**
After the upgrade, I have archived a submission. However, the Malware Archive isn't showing anything - until I choose to "include supplementary files". Then I see both supplementary and not supplementary files. There are no errors visible in the archiver logs.

**To Reproduce**
1. Go to a submission and send it to the archive.
2. Wait a while to let Archiver do its work
3. Open Malware Archive UI
4. See nothing
5. Click on "include supplementary files"
6. See files from the archived submission
7. Click on "exclude supplementary files"
8. See nothing again.

**Expected behavior**
Non-supplementary files are seen without any filtering change.

**Screenshots**
For 4 & 8:
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/7854acad-2250-4233-89f7-9e226790af89)

For 6:
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/646e04fd-c0c7-4ec2-ba85-2607b8f0e8bc)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: stable91
 - Browser: Firefox

## Not showing previously archived files

**Describe the bug**
I have started sending submissions to the archive some time ago to have it filled once the UI migrates to the stable path. Unfortunately, they are not visible in the Malware Archive at all, although I can see `archived:true` in the ES submission index.

Note: If the answer is _Archiver wasn't ready before, so it cannot work_, it's alright.

**To Reproduce**
1. Using AL in version `stable90`, open a submission and send it to the archive.
2. Wait until the submission is properly archived.
3. Update AL to `stable91`
4. Open Malware Archive
5. See nothing

**Expected behavior**
Previously archived files are visible in the Malware Archive after the update.

**Additional context**

I wanted to verify if files were archived. Surprisingly, I haven't found any meaningful information in the file index (`archive_ts = null` as well as `from_archive = false` for both previously and freshly archived files), but I found the `archived` field in `submission` index. Here, looking with the following query:

```json
GET submission/_search
{
  "query": {
    "match": {"archived": "true"}
  },
  "size": 100
}
```

I got 20 results, including old (before upgrade) and new (after upgrade) submissions. There is one difference I found in `file` index between files from old and new submissions: the old ones don't have `is_supplementary` field.

## (?) Expire removes archived submissions?

I'm not sure if it's actually a bug, but I've found out that I can find in the Elasticsearch only those archived submissions, that aren't expired. This makes me worried that maybe they are mistakenly removed on expiration date - but perhaps it is designed so? (although, the default Archiver configuration as `['file', 'submission', 'result']` suggests a little different). Or it's just because the archive wasn't yet officially integrated, and I have just tried to use something that weren't working?

## Feedback: submission view

It would be nice to have easily-accessible view of archived submissions. The `archived:true` query in the Subimission tab is enough, but would be nice to have it easier accessible (a button? or a feature to save queries, as in alerter view?)
