### ISSUE TITLE
Feature Request: tolerations and nodeAffinity

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline#221]
**Is your feature request related to a problem? Please describe.**
I've been given a dedicated node cluster with sufficient resources for AssemblyLine, but I need to define it using the tolerations and nodeAffinity.  Currently, core components allow you to define the nodeAffinity, but not tolerations.  Services don't allow you to define either nodeAffinity or tolerations as it's managed by the Scaler.

**Describe the solution you'd like**
I'd like to be able to define the tolerations and nodeAffinity for core and services in the Helm file.

**Describe alternatives you've considered**
I've made the changes to allow core to use the tolerations, but it doesn't apply to services.  When services spin up, they run out of resources.  It seems the service change is currently beyond the helm charts.

**Comment by cccs-rs** [comment]
Would the `scaler.linux_node_selector` configuration work in this case as you would just need to specify the selector (whether it be based on fields or labels) that correspond to the node?

https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#scaler

**Comment by eljeffeg** [comment]
From what I can tell, Field and Label selectors cannot be used directly dictate scheduling behaviors such as tolerations or node affinity.

**Comment by eljeffeg** [comment]
I'd also like the ability for service pods to use `imagePullSecrets`.

**Comment by cccs-rs** [comment]
Looks like the configuration for the `linux_node_selector` should translate to a nodeAffinity for the service pods:
https://github.com/CybercentreCanada/assemblyline-core/blob/14bfcd276ac904882724c4eb9075fe0350cf9f3f/assemblyline_core/scaler/controllers/kubernetes_ctl.py#L140

So we would just need to add a configuration for tolerations.

**Comment by cccs-rs** [comment]
You can test with [this](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.1.dev143) development release to make sure you can configure the system as necessary when we merge this into stable.

**Comment by eljeffeg** [comment]
@cccs-rs I pulled the latest dev images and updated my helm charts, but wasn't able to get the nodeAffinity and tolerations on Services.  They did show up on all the core services.  Here are my respective value.yaml config.

```yaml
# An affinity to be applied to all core (non-service) pods not provided by imported charts.
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#NodeAffinity
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: dedicated
        operator: In
        values:
        - assemblyline

# The tolerations to be applied to all core (non-service) pods not provided by imported charts.
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#tolerations
tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: assemblyline
    
configuration:
  core:
    scaler:
      linux_node_selector:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - assemblyline
```

**Comment by cccs-rs** [comment]
> ```yaml
> configuration:
>   core:
>     scaler:
>       linux_node_selector:
>         requiredDuringSchedulingIgnoredDuringExecution:
>           nodeSelectorTerms:
>           - matchExpressions:
>             - key: dedicated
>               operator: In
>               values:
>               - assemblyline
> ```

This would have to be updated to (based on [docs](https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#selector)): 
```yaml
configuration:
  core:
    scaler:
      linux_node_selector:
        label:
          - key: dedicated
            operator: In
            values: 
              - assemblyline
```
