### ISSUE TITLE
PortName is requeried for Multi-port Services

### ISSUE THREAD

**Issue by kulukami** [CybercentreCanada/assemblyline#279]
**Is your feature request related to a problem? Please describe.**

container.ports [] set multiple ports in service_manifest.yml, but only first one 5003 shown in k8s control dashboard.

Here is the [scaler kubernetes_ctl.py](https://github.com/CybercentreCanada/assemblyline-core/blob/master/assemblyline_core/scaler/controllers/kubernetes_ctl.py#L1145), it parse spec.container.ports as a list[int]
```python
service.spec.ports = [V1ServicePort(port=int(_p)) for _p in spec.container.ports]
```

But as k8s docs describes:

<b>[Multi-port Services](https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services)</b>
For some Services, you need to expose more than one port. Kubernetes lets you configure multiple port definitions on a Service object. When using multiple ports for a Service, **you must give all of your ports names** so that these are unambiguous. For example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
```

**Describe the solution you'd like**
A update for [odm.module of DockerConfig ports](https://github.com/CybercentreCanada/assemblyline-base/blob/master/assemblyline/odm/models/service.py#L43) like the k8s ports: [V1ServicePort](https://github.com/kubernetes-client/python/blob/f414832bb05b946eb1758df12f08806b44dd315e/kubernetes/client/models/v1_service_port.py#L21)

Or simply adding name for each port while creating k8s pods in [scaler kubernetes_ctl.py](https://github.com/CybercentreCanada/assemblyline-core/blob/master/assemblyline_core/scaler/controllers/kubernetes_ctl.py#L1145),
```python
service.spec.ports = [V1ServicePort(port=int(_p),name="port_{}".format(spec.container.ports.index(_p))) for _p in spec.container.ports]
```
