### ISSUE TITLE
Adding CAPE service to an air-gapped Assembly Line

### ISSUE THREAD

**Issue by kareemauth** [CybercentreCanada/assemblyline#321]
We have deployed Assembly Line onto an air gapped network and I would like some clarification on adding the CAPE service. We have a functional CAPE server within the same network. The Assembly Line server has been fully built within this network with a connection to our local Docker registry to pull the container images. The CAPE service was added through the front end GUI using the service manifest with changes to point to the local Docker registry to obtain the image

```
docker_config:
   allow_internet_access: true
   image: <REGISTRY IP>/cccs/assemblyline-service-cape:4.4.0.62
   cpu_cores: 1
   ram_mb: 2000

dependencies:
   updates:
      container:
        cpu_cores: 2.0
        ram_mb: 4096
        allow_internet_access: true
        command: ["python", "-m", "cape.update_server"]
        image: <REGISTRY IP>/cccs/assemblyline-service-cape:4.4.0.62
        ports: ["5003"]
      run_as_core: True
```

Assembly Line is a single server hosting a MicroK8s installation and using the helm chart to deploy the application.

The CAPE service pod is failing to run due to a readiness probe waiting on cape-updates. When I look at the logs for the cape-updates pod the error I receive is:

`no module named cape.update_server`

I have the CAPE update_server.py but not sure where it needs to be placed and looking to clarify my understanding of deploying the CAPE service
