### ISSUE TITLE
Broken submission profiles on ingest and resubmit

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#346]
**Describe the bug**
Context: https://discord.com/channels/908084610158714900/908717528082173983/1363918464682693000

tl;dr: submission profiles work well when using UI submission on the front page, but ingest API or "resubmit" button are broken. Works a little better for new user. In addition, some options seem wrongly described.

When uploading a file using submission profile:
 - for a user existing before migration, the selected service list is empty and submission is dispatched on all enabled services
 - for a new user, the list seems to be reset to the default
 - `service_spec` seems to be kept in all cases
 - user-specific modifications of service configuration seem to be applied to 30% of ingest request (this is funny)
 - `generate_alert` from submission profile is being ignored.

When having an uploaded file and trying to resubmit using a profile as an existing user, the service list can again be emptied, but alert generation seems to be kept. In the context of profiles below, I observed emptying the list for `VirusTotal`, but not for `static` or `dynamic`.

Translation is a little confusing when it comes to the filtering: almost every place says about excluding filtering services, but in user settings it's about allowing filtering services - but works as excluding.

I haven't observed such problems when using upload from the main page. My idea is that maybe something breaks when merging with user's settings. 

**To Reproduce**

My current profile submissions are:

```yaml
  profiles:
    - name: "static"
      description: "Static + PKG Observer"
      display_name: "Standard Analysis"
      params:
        ignore_filtering: false
        ignore_cache: false
        generate_alert: true
        ttl: 14
        services:
          selected: ["Filtering", "Antivirus", "Static Analysis", "Extraction", "Networking", "PKG-Observer-Service"]
          # excluded: ["Suricata"]
        service_spec:
          DocumentPreview:
            max_page_rendered: 2
    - name: "dynamic"
      description: "Dynamic analysis"
      display_name: "Dynamic Analysis"
      params:
        ignore_filtering: false
        ignore_cache: false
        generate_alert: true
        ttl: 14
        services:
          selected: ["Filtering", "Antivirus", "Static Analysis", "Extraction", "Networking", "Dynamic Analysis"]
          # excluded: ["Suricata"]
        service_spec:
          DocumentPreview:
            max_page_rendered: 2
    - name: "VirusTotal"
      description: "VirusTotal analysis without extractions"
      display_name: "VirusTotal Analysis"
      params:
        ignore_filtering: false
        ignore_cache: false
        generate_alert: true
        ttl: 14
        services:
          selected: ["Filtering", "Antivirus", "Static Analysis", "Networking", "VirusTotal"]
          # excluded: ["Suricata"]
        service_spec:
          DocumentPreview:
            max_page_rendered: 2
    - name: "dir_listings"
      description: "Simple Downloader configured to handle directory listings, 3 levels deep"
      display_name: "Download directory listings"
      params:
        ignore_filtering: false
        ignore_cache: false
        generate_alert: true
        ttl: 14
        services:
          selected: ["Filtering", "Antivirus", "Static Analysis", "Extraction", "Networking", "Simple-Downloader"]
          excluded: []
        service_spec:
          DocumentPreview:
            max_page_rendered: 2
          Simple-Downloader:
            extract_dir_listing_as_urls: true
            extract_directories_from_listing: true
            extraction_depth: 3
```

**Expected behavior**
Submission profiles are respected on ingest and resubmitting.

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.6.0.0
 - Browser: [e.g. chrome, safari]

**Additional context**
