### ISSUE TITLE
log-storage error after pod deletion

### ISSUE THREAD

**Issue by dan-acsc** [CybercentreCanada/assemblyline#69]
**Problem**
In the helm chart values.yaml file by default log-storage is configured with 1 replica.

chart/assemblyline/values.yaml
```yaml
log-storage:
  clusterName: "log-storage"
  replicas: 1 # needs to be greater than 1
```

If the pod is deleted or restarts for any reason it will fail to come up, and all dependent pods will fail without about 6 being down.

The reason for this is that elasticsearch will have it's status set to yellow, because it won't have enough nodes to allocate it's shards to. Because the master node won't allocate to itself.

**Solution** 
Change the replica count for log-storage to 2 or 3.

**Comment by cccs-rs** [comment]
Is there any particulars that you can describe about this issue?

I was able to start up a single-node log-storage instance and forcefully terminate the pod and it was able to recover successfully.

**Comment by cccs-rs** [comment]
Any updates on this issue?

**Comment by dan-acsc** [comment]
I think you'd have to run some data through the system first, other than that there isn't much else special about the configuration.

The other key part of the configuration is having seperateInternalELKStack set

section of the values.yaml file:
```
internalFilestore: false
enableLogging: true
enableMetrics: true
enableAPM: false
internalELKStack: true
seperateInternalELKStack: true
loggingUsername: elastic
loggingTLSVerify: none
```

I'll try and re-produce and give you the values.yaml file in the next couple of days.

**Comment by dan-acsc** [comment]
If you deploy the following values.yaml file and delete the pod `log-storage-master-0`


It will never come back up, it'll sit there `running 0/1` because it's readiness probe will never succeed.

Also the `es-metrics` pod will crash after a while and not come back up.

values.yaml
```yaml
# 1. Setup the ingress controller
ingressAnnotations:
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/proxy-body-size: 100M
  cert-manager.io/cluster-issuer: vault-clusterissuer-azr
tlsSecretName: assemblyline-tls


# 2. Setup the storage classes and fine tune the datastore to meet the needs of the Kubernetes cluster
redisStorageClass: "managed-csi"
datastore:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 12Gi
    limits:
      cpu: 2
      memory: 20Gi
  volumeClaimTemplate:
    storageClassName: "managed-csi"

log-storage:
  replicas: 1
  volumeClaimTemplate:
    storageClassName: "managed-csi"

persistantStorageClass: "managed-csi"

# Don't use an internal filestore unless there is no alternative (use blob storage instead)
internalFilestore: true

# 4. This enables a seperate internal ELK Log stack
# Have Assemblyline send logs to the configured ELK stack
enableLogging: true
# Have Assemblyline send metrics to the configured ELK stack
enableMetrics: true
# This would have Assemblyline send APM metrics to the
#  configured ELK stack as well but it is very costly in 
#  terms of resources so only turn it on if you really
#  need insight on API response time and core components
#  operation timing.
enableAPM: false
# We are setting up an internal ELK stack so we can turn that on
internalELKStack: true
# Because this is a cluster, we will have Assemblyline spin up 
#  a completely different elastic database so the logging does not 
#  interfere with the performance of the data
seperateInternalELKStack: true
# The internal ELK stack use elastic as its base username and
#  does not verify TLS
loggingUsername: elastic
loggingTLSVerify: none

configuration:
  # Set the fully qualified domain name
  ui:
    fqdn: "assemblyline.acsc.internal"
    # Enforce submission quotas for individual users.
    enforce_quota: false
    # Timeout after which a stale session is no longer valid
    session_duration: 3600
    # Should we validate that the session comes from the same IP? - Note this is set to false because I was continually getting logged out while using the API
    validate_session_ip: false
    # Should we validate that the session uses the same user agent - Note this is set to false because I was continually getting logged out while using the API
    validate_session_useragent: false
    # TODO replace with kuberntes secret or other encrypted value.
    secret_key: testsecretkeyshoulddefinitelyreplace

  # Whether to use the internal authentification / LDAP or OAuth refer to https://cybercentrecanada.github.io/assemblyline4_docs/installation/configuration/authentication/ for details
  auth:
    internal:
      enabled: true

  # Use Azure blob storage (currently this requires a Storage account named assemblylinemainblob and it needs to contain two containers called "cache" and "storage")
  filestore:
    cache: ["s3://${INTERNAL_FILESTORE_ACCESS}:${INTERNAL_FILESTORE_KEY}@filestore:9000?s3_bucket=al-cache&use_ssl=False"]
    storage: ["s3://${INTERNAL_FILESTORE_ACCESS}:${INTERNAL_FILESTORE_KEY}@filestore:9000?s3_bucket=al-storage&use_ssl=False"]

  system:
    # Path path to the constants module
    constants: assemblyline.common.constants

    # Organisation Name
    organisation: Any

    # Type of system. If different then production, watermark will be shown in the UI
    type: production

  core:
    alerter:
      # Time to live in days for alerts in the system
      alert_ttl: 90

      # List of fields that should keep the same value in between normal and extended scan
      #  NOTE: You should not have to change those ever, this might get removed in the future
      constant_alert_fields:
      - alert_id
      - file
      - ts

      # Default field to group alerts with in the UI
      default_group_field: file.sha256

      # Delay applied to the alert UI to leave time to the extended scan to complete
      delay: 300

      # List of fields allowed to be used for grouping that are present in every single alerts
      filtering_group_fields:
      - file.name
      - status
      - priority

      # List of fields allowed to be used for grouping that are present only in a subset of alerts
      non_filtering_group_fields:
      - file.md5
      - file.sha1
      - file.sha256

      # Python class used to process alert messages
      #   NOTE: This should not be changed unless you've built your own container with
      #         extra packages with alert processing capability
      process_alert_message: assemblyline_core.alerter.processing.process_alert_message
    # Enable large scale cleanup
```
