### ISSUE TITLE
Adding backend services on Azure AKS results in the update jobs hanging indefinitely

### ISSUE THREAD

**Issue by 0xMack** [CybercentreCanada/assemblyline#97]
**Description**
Adding backend services on Azure AKS results in the update jobs hanging indefinitely. The service installations worked during the initial release but seem to have stopped working following some helm chart upgrades.  However, adding a service by pasting the manifest in the UI still works.

**Expected behavior**
Clicking the button on the ui to install an available service should install that service and deploy it to the kubernetes cluster.

**Screenshots**
![image](https://github.com/CybercentreCanada/assemblyline/assets/15696553/1d226792-0950-48b6-9584-2a66b352d369)
![image](https://github.com/CybercentreCanada/assemblyline/assets/15696553/4b5dcb7e-80fc-4a46-8039-6f3daac6f6a9)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.stable
 - Kubernetes Version: 1.25.11

**Deployment Configuration**
Assemblyline was deployed to Azure AKS, following the steps described here https://cybercentrecanada.github.io/assemblyline4_docs/installation/cluster/general/

The values used to override the helm chart defaults are provided below.

```
ingressAnnotations:
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/proxy-body-size: 100M

redisStorageClass: azureblob-fuse-premium
datastore:
  replicas: 2
  volumeClaimTemplate:
    storageClassName: azureblob-fuse-premium
    resources:
      requests:
        storage: 300Gi
log-storage:
  replicas: 2
  volumeClaimTemplate:
    storageClassName: azureblob-fuse-premium
    resources:
      requests:
        storage: 100Gi
persistantStorageClass: azureblob-fuse-premium

internalFilestore: false


enableLogging: true
enableMetrics: true
enableAPM: false
internalELKStack: true
seperateInternalELKStack: true
loggingUsername: elastic
loggingTLSVerify: "none"

createAdminAccount: "always"

configuration:
  submission:
    max_file_size: 104857600
  ui:
    fqdn: ${FQDN}

  filestore:
    cache: ["${FILESTORE_URL}?${FILESTORE_PASSWORD}"]
    storage: ["${FILESTORE_URL}?${FILESTORE_PASSWORD}"]

  logging:
    log_level: INFO

kibana:
  elasticsearchHosts: http://log-storage-master:9200
  kibanaConfig:
    kibana.yml: |
      elasticsearch:
        ssl.certificateAuthorities: ''

```
